name: Golang Testing

description: "Action for running golang testing"

inputs:
  go-version:
    description: "Version of golang"
    default: "1.21.x"

runs:
  using: "composite"
  steps:

    - name: Install required dependencies
      shell: bash
      run: go install gotest.tools/gotestsum@ec99a250836f069a524bb9d9b5de0a7a96334ea7 # v1.11.0

    - name: Run unit tests
      shell: bash
      run: |
        gotestsum --format github-actions --no-color --format-hide-empty-pkg --junitfile report.xml

    - name: Run pre-deployment tests
      shell: bash
      run: |
        if make -n pre-deploy-test >/dev/null 2>&1; then
          make pre-deploy-test
        fi

    - name: Generate test summary
      uses: test-summary/action@fee35d7df20790255fe6aa92cf0f6d28092ecf2f # v2.2
      with:
        paths: |
          report.xml            
      if: always()