name: Deploy Serverless

description: "Action for deploying AWS serverless"

inputs:
  run-install:
    description: "Whether to run npm ci"
    required: true
    default: "false"
  
  deploy-args:
    description: "Additional args to deploy"

runs:
  using: "composite"
  steps:
    - name: Install required dependencies
      uses: exzeo-devops/action-workflows/.github/actions/serverless-install@DOPS-5528

    - name: Check
      shell: bash
      run: |
        ls bin/sem

    # - name: Deploy serverless
    #   shell: bash
    #   run: |
    #     if make -n deploy >/dev/null 2>&1; then
    #       make deploy
    #     else
    #       sls deploy ${{ inputs.deploy-args }}
    #     fi

    - name: Post-Deployment Testing
      shell: bash
      run: |
        if make -n post-deploy-test >/dev/null 2>&1; then
          make post-deploy-test
        fi        