name: Golang Security Checks

description: "Action for checking golang security"

runs:
  using: "composite"
  steps:
    - name: Install required dependencies
      shell: bash
      run: |
        go install github.com/zricethezav/gitleaks/v8@dab7d0292ad7ebc52c7adfcad755f92e2f7c9a9a # v8.18.1

    - name: Run gitleaks (Scan for hard-coded secrets in git repository)
      shell: bash
      run: gitleaks detect --verbose

    # - uses: gitleaks/gitleaks-action@v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

    - name: Run GoSec (Golang code issues)
      uses: securego/gosec@55d79496019a560e16e73e1948dee20a1fad631a # v2.18.2
      with:
        args: ./...

    - name: Run govulncheck (Golang CLI issues)
      uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4 # v1.0.1