name: Assume Role

description: "Action for assume AWS role"

inputs:
  role-arn:
    description: "AWS Role Arn to assume"
    required: true

  audience:
    description: "OIDC Audience"
    required: true

  region:
    description: "AWS Region"
    required: true
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: ${{ inputs.audience }}
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.region }}