name: Deploy

description: "Action for deploying AWS serverless functions"

inputs:
  role-arn:
    description: "AWS Role Arn to assume"
    required: true

  audience:
    description: "OIDC Audience"
    required: true

  region:
    description: "AWS Region"
    required: true
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        audience: ${{ inputs.audience }}
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.region }}

    - name: Check if "make test" exists
      id: make-test
      shell: bash
      run: |
        make -q -n test > /dev/null 2>&1
      continue-on-error: true

    - name: Run tests
      if: steps.make-test.outcome == 'success'
      shell: bash
      run: |
        make test