name: Deploy Serverless

description: "Action for deploying AWS serverless"

inputs:
  node-version:
    description: "NodeJS version"
    required: true
    default: "lts"

  run-install:
    description: "Whether to run npm ci"
    required: true
    default: "false"
  
  deploy-args:
    description: "Additional args to deploy"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Use Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run 'npm install'
      if: inputs.run-install == 'true'
      shell: bash
      run: npm ci

    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.7'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: Install Serverless Framework
      shell: bash
      run: npm install -g serverless

    - name: Deploy serverless
      shell: bash
      run: |
        if make -n deploy >/dev/null 2>&1; then
          make deploy
        else
          sls deploy ${{ inputs.deploy-args }}
        fi