name: Validate Serverless

description: "Action for validating AWS serverless"

inputs:
  node-version:
    description: "NodeJS version"
    required: true
    default: "lts"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.7'

    - name: Install Cloudformation Linter
      shell: bash
      run: |
        pip install cfn-lint cfn-lint-serverless

    - name: serverless package
      uses: serverless/github-action@v3.2
      with:
        args: package

    - name: Run cf-lint
      shell: bash
      run: |
        cfn-lint .serverless/cloudformation-template-*.json -a cfn_lint_serverless.rules -i W3005 -i ES4000 -i ES1007