name: Install golang

description: "Action for installing golang"

inputs:
  version:
    required: false
    description: "Version of golang to install"
    default: "stable"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Check if .go-version file exists
      shell: bash
      id: check_files
      run: |
        if [ -f .go-version ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi        

    - name: Setup Go by file
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      if: ${{ steps.check_files.outputs.exists == 'true' }}
      with:
        go-version-file: .go-version

    - name: Setup Go by version
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      if: ${{ steps.check_files.outputs.exists == 'false' }}
      with:
        go-version: "${{ inputs.version }}"