name: Install required serverless dependencies

description: "Action for install serverless"

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: "20.x"

    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: "3.9"

    - name: Install required dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install cfn-lint cfn-lint-serverless awscli

    - name: Install serverless
      shell: bash
      run: npm install -g serverless          