name: Deploy Serverless

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_OIDC_AUDIENCE:
        required: true

env:
  ROLE_ARN: "${{ vars.ROLE_ARN }}"

jobs:
  deploy:
    name: "Deploy Serverless"
    runs-on: self-hosted
    environment: "${{ inputs.environment }}"

    permissions:
      id-token: write
      contents: read    

    steps:

      - name: Assume Role
        uses: exzeo-devops/action-workflows/.github/actions/aws-assume-role@main
        timeout-minutes: 2 # should never take this long, if it times out, something is wrong
        with:
          role-arn: ${{ env.ROLE_ARN }}
          audience: ${{ secrets.AWS_OIDC_AUDIENCE }}

      - name: Deploy Serverless
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: exzeo-devops/action-workflows/.github/actions/deploy-serverless@main
